POST http://localhost:8080/api/v1/management/request
Content-Type: application/json

{
  "firstname": "Seifeddine",
  "lastname": "Abidi",
  "email":  "seifeddine.abidi@esprit.tn",
  "password": "password",
  "role":  "ADMIN"
}